import unittest
from solution import RecipeBook

class TestRecipeBook(unittest.TestCase):

    def test_initialize_recipe_book(self):
        # This function should initialize a recipe book
        # For the sake of this example, we will just check if it exists
        my_book = RecipeBook("MyBook")
        self.assertIsNotNone(my_book)
        self.assertEqual(my_book.name, "MyBook")

#This was generated by the AI, but it is not used in the solution.
# def test_create_recipe_book():
#     recipe = create_recipe("Pasta", "Boil water, add pasta, cook for 10 minutes.")
#     assert recipe['name'] == "Pasta"
#     assert recipe['instructions'] == "Boil water, add pasta, cook for 10 minutes."


from solution import Recipe, RecipeIngredient, Ingredient, DietaryTag
from constants import MeasurementUnits
class TestRecipe(unittest.TestCase):
    
    def test_initialize_recipe(self):
        # This function should initialize a recipe
        tomato = Ingredient("Tomato", [DietaryTag.VEGAN, DietaryTag.VEGETARIAN])
        pasta = Ingredient("Pasta", [DietaryTag.VEGAN, DietaryTag.VEGETARIAN])
        two_tomatoes = RecipeIngredient(tomato, 2, MeasurementUnits.COUNT)
        pasta_4oz = RecipeIngredient(pasta, 4, MeasurementUnits.OZ)
        pasta_name = "Pasta with Tomato"
        my_recipe = Recipe(pasta_name, [two_tomatoes, pasta_4oz])
        self.assertIsNotNone(my_recipe)
        self.assertEqual(my_recipe.name, pasta_name)
        self.assertListEqual(my_recipe.ingredients, [two_tomatoes, pasta_4oz])

    def test_get_dietary_tags(self):
        tomato = Ingredient("Tomato", {DietaryTag.VEGAN, DietaryTag.VEGETARIAN, DietaryTag.GLUTEN_FREE, DietaryTag.NUT_FREE})
        egg = Ingredient("Egg", {DietaryTag.NON_VEGETARIAN, DietaryTag.GLUTEN_FREE, DietaryTag.NUT_FREE})
        salt = Ingredient("Salt", {DietaryTag.VEGAN, DietaryTag.VEGETARIAN, DietaryTag.GLUTEN_FREE, DietaryTag.NUT_FREE})
        pinenut = Ingredient("PineNut", {DietaryTag.VEGAN, DietaryTag.VEGETARIAN, DietaryTag.GLUTEN_FREE})
        one_tomato = RecipeIngredient(tomato, 1, MeasurementUnits.COUNT)
        three_eggs = RecipeIngredient(egg, 3, MeasurementUnits.COUNT)
        topping_pinenut = RecipeIngredient(pinenut, 1, MeasurementUnits.TEA_SPOON)
        salt_to_taste = RecipeIngredient(salt, 0, MeasurementUnits.TO_TASTE)
        omlet = Recipe("Omlet", [three_eggs, one_tomato, topping_pinenut, salt_to_taste])
        expected_dietary_tags = sorted({DietaryTag.VEGAN, DietaryTag.VEGETARIAN, DietaryTag.GLUTEN_FREE, DietaryTag.NUT_FREE, DietaryTag.NON_VEGETARIAN })
        self.assertListEqual(expected_dietary_tags, sorted(omlet.get_dietary_tags()))
    
    def test_empty_dietary_tags_for_no_recipe_ingredients(self):
        zero_ingredients_recipe = Recipe("Zero Ingredients", [])
        self.assertEqual(set(), zero_ingredients_recipe.get_dietary_tags())
