import unittest
from solution import RecipeBook

class TestRecipeBook(unittest.TestCase):

    def test_initialize_recipe_book(self):
        # This function should initialize a recipe book
        # For the sake of this example, we will just check if it exists
        my_book = RecipeBook("MyBook")
        self.assertIsNotNone(my_book)
        self.assertEqual(my_book.name, "MyBook")

#This was generated by the AI, but it is not used in the solution.
# def test_create_recipe_book():
#     recipe = create_recipe("Pasta", "Boil water, add pasta, cook for 10 minutes.")
#     assert recipe['name'] == "Pasta"
#     assert recipe['instructions'] == "Boil water, add pasta, cook for 10 minutes."